from pycloc.utils.CLOCException import CLOCException
